print('hello world')
print('my name is giorgi')
print('my lastname is samsonidze')
print('i am 15 years old')
print('i will be best proggramer')
print('now i dont have any game in my laptop')
print('i will always make homeworks and classworks')
print('i like GOA academy')
print('i want to make big programs like big programmers')
print('so remember me i am GIORGI SAMSONIDZE')
print('so remember me i am GIORGI SAMSONIDZE')
print('so remember me i am GIORGI SAMSONIDZE')
print('so remember me i am GIORGI SAMSONIDZE')
print('so remember me i am GIORGI SAMSONIDZE')
print('so remember me i am GIORGI SAMSONIDZE')
print('so remember me i am GIORGI SAMSONIDZE')
print('so remember me i am GIORGI SAMSONIDZE')
print('so remember me i am GIORGI SAMSONIDZE')
print('so remember me i am GIORGI SAMSONIDZE')
print('so remember me i am GIORGI SAMSONIDZE')