text_1 = str(input('enter any text'))
text_2 = str(input('enter any text'))
text_3 = str(input('enter any text'))
text_4 = str(input('enter any text'))
text_5 = str(input('enter any text'))
text_6 = str(input('enter any text'))
text_7 = str(input('enter any text'))
text_8 = str(input('enter any text'))
text_9 = str(input('enter any text'))
text_10 = str(input('enter any text'))

num_1 = int(input('enter any number'))
num_2 = int(input('enter any number'))
num_3 = int(input('enter any number'))
num_4 = int(input('enter any number'))
num_5 = int(input('enter any number'))
num_6 = int(input('enter any number'))
num_7 = int(input('enter any number'))
num_8 = int(input('enter any number'))
num_9 = int(input('enter any number'))
num_10 = int(input('enter any number'))


float_1 = float(input('enter any decimal number'))
float_2 = float(input('enter any decimal number'))
float_3 = float(input('enter any decimal number'))
float_4 = float(input('enter any decimal number'))
float_5 = float(input('enter any decimal number'))
float_6 = float(input('enter any decimal number'))
float_7 = float(input('enter any decimal number'))
float_8 = float(input('enter any decimal number'))
float_9 = float(input('enter any decimal number'))
float_10 = float(input('enter any decimal number'))